from oci_generated import *

# defines constants that could not be generated by ctypesgen

# broken because lhs is #defined first.
# /home/lameiro/projects/cx_oracle_on_ctypes/instantclient_11_2/sdk/include/oci.h: 1408
try:
    OCI_ATTR_ENV_NCHARSET_ID = OCI_ATTR_NCHARSET_ID
except:
    pass

# ctypesgen wrongly generated sb1 as char

sb1 = ctypes.c_byte